version: "3.9"

services:
  twimap:
    build: .
    command: python -m twimap.server
    volumes:
      - .:/app
    ports:
      - "9000:9000"

networks:
  default:
    name: default_network
    external: true